# Generated by Django 3.0.2 on 2020-01-30 17:09

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('site_code', models.CharField(default='XXX', max_length=3, primary_key=True, serialize=False)),
                ('site_name', models.CharField(max_length=50)),
                ('site_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('site_date_added', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Observations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when_observed', models.DateTimeField()),
                ('conditions', models.CharField(max_length=225)),
                ('visibility', models.IntegerField()),
                ('comments', models.CharField(max_length=225)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observations.Site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
