# Generated by Django 3.0.2 on 2020-01-31 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0003_auto_20200131_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='site_description',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
