# Generated by Django 3.0.2 on 2020-01-31 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0004_site_site_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='site_description',
            field=models.TextField(blank=True, max_length=225, null=True),
        ),
    ]
