# Generated by Django 3.0.2 on 2020-02-01 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0005_auto_20200131_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='visability',
            new_name='visibility',
        ),
    ]
